# rollback change
---
- hosts: "{{ hosts_group }}"
  name: "rollback change with Ansible"
  tasks:
    - name: (block) update and restart nginx
      block:
        - name: Update default site
          ansible.builtin.template:
            src: templates/fixed-index.html.j2
            dest: /usr/share/nginx/html/index.html
            owner: root
            group: root
            mode: '0644'
        - name: Update default site
          ansible.builtin.template:
            src: templates/fixed-nginx.conf.j2
            dest: /etc/nginx/nginx.conf
            owner: root
            group: root
            mode: '0644'
        - name: restart nginx service
          ansible.builtin.systemd:
            name: nginx
            state: restarted

    - name: "send Dynatrace custom configuration event with business context information"
      uri:
        url: "{{ dt_api_url }}/v1/events"
        method: POST
        headers:
          content-type: application/json
          Authorization: "Api-Token {{ dt_api_token }}"
        body:
          eventType: CUSTOM_CONFIGURATION
          attachRules:
            tagRule:
            - meTypes:
              - SERVICE
              - PROCESS_GROUP
              - HOST
              tags:
              - context: CONTEXTLESS
                key: "{{ configuration_tag_key }}"
                value: "{{ configuration_tag_value }}"
          source: "Ansible Automation Platform"
          description: "{{ configuration_details }}"
          configuration: "{{ configuration_type }}"
          customProperties:
            Change New: "{{ configuration_new }}"
            Change Old: "{{ configuration_old }}"
            Remediation: "{{ configuration_remediation }}"
        body_format: json
        status_code: 200, 201
