# initiate change
---
- name: "initiate change with Ansible"
  hosts: "{{ hosts_group }}"
  tasks:
    - name: (block) update and restart nginx
      block:
        - name: Update index.html
          ansible.builtin.template:
            src: templates/changed-index.html.j2
            dest: /usr/share/nginx/html/index.html
            owner: root
            group: root
            mode: '0644'
        - name: Update nginx.conf
          ansible.builtin.template:
            src: templates/broken-nginx.conf.j2
            dest: /etc/nginx/nginx.conf
            owner: root
            group: root
            mode: '0644'
        - name: restart nginx service
          ansible.builtin.systemd:
            name: nginx
            state: restarted
          ignore_errors: yes

    
    # https://www.dynatrace.com/support/help/dynatrace-api/environment-api/events-v1/post-event
    - name: "send Dynatrace custom configuration event with business context information"
      ansible.builtin.uri:
        url: "{{ dt_api_url }}/v1/events"
        method: POST
        headers:
          content-type: application/json
          Authorization: "Api-Token {{ dt_api_token }}"
        body:
          eventType: CUSTOM_CONFIGURATION
          title: "Configuration Change"
          attachRules:
            tagRule:
            - meTypes:
              - SERVICE
              - PROCESS_GROUP_INSTANCE
              - HOST
              tags:
              - context: CONTEXTLESS
                key: "{{ configuration_tag_key }}"
                value: "{{ configuration_tag_value }}"
          source: "Ansible Automation Platform"
          description: "{{ configuration_details }}"
          configuration: "{{ configuration_type }}"
          customProperties:
            Change New: "{{ configuration_new }}"
            Change Old: "{{ configuration_old }}"
            Remediation: "{{ configuration_remediation }}"
        body_format: json
        status_code: 200, 201
      register: dynatrace_custom_event

    - name: Show results of API call
      ansible.builtin.debug:
        msg: "{{ dynatrace_custom_event }}"


