# rollback deployment
---
- hosts: "{{ hosts_group }}"
  name: "rollback deployment with Ansible"
  tasks:
    - name: "Rollback nodejs deployment"
      block:
        - name: Restore working file
          ansible.builtin.template:
            src: "templates/{{ application_filename }}.j2"
            dest: "{{ application_working_dir }}/{{ application_filename }}"
            force: yes
        - name: Restart the application
          ansible.builtin.shell: |
            /usr/local/lib/npm/bin/pm2 start {{ application_working_dir }}/{{ application_filename }}
    
    - name: "push Dynatrace custom deployment event"
      ansible.builtin.uri:
        url: "{{ dt_api_url }}/v1/events"
        method: POST
        headers:
          content-type: application/json
          Authorization: "Api-Token {{ dt_api_token }}"
        body:
          eventType: CUSTOM_DEPLOYMENT
          attachRules:
            tagRule:
            - meTypes:
              - SERVICE
              - PROCESS_GROUP_INSTANCE
              - HOST
              tags:
              - context: CONTEXTLESS
                key: "{{ deployment_tag_key }}"
                value: "{{ deployment_tag_value }}"
          source: "Ansible Automation Platform"
          deploymentName: "{{ deployment_name }}"
          deploymentVersion: "{{ deployment_version}}"
          remediationAction: "{{ deployment_remediation }}"
          customProperties:
            Details: "{{ deployment_details }}"
            Feature Flag: "{{ deployment_feature }}"
        body_format: json
        status_code: 200
